"""
AUTO-GENERATED LMDB Schema Definitions
================================================================================
Source: Pydantic models in ohio-legal-ai.io/packages/models
Generated: 2025-11-25 20:38:24

DO NOT EDIT THIS FILE MANUALLY
Run: python packages/models/09_lmdb_schema_generator.py

PURPOSE:
  These TypedDict schemas ensure LMDB builders output data structures that
  exactly match the Pydantic models used by the application API layer.

USAGE IN LMDB BUILDERS:
  from generated_schemas import OhioSectionDict

  def build_entry(data) -> OhioSectionDict:
      entry: OhioSectionDict = {
          "section_number": data['section_number'],
          "url": data['url'],
          # ... type checker validates all fields
      }
      return entry

WORKFLOW:
  1. Edit Pydantic model in application repo
  2. Run code generators (00_generate_all.py)
  3. This file auto-updates with new schema
  4. Rebuild LMDB with updated schema
  5. Application reads LMDB → maps to Pydantic (guaranteed match)
================================================================================
"""

from typing import TypedDict, NotRequired, Optional, List, Literal, Dict, Any, Union
from datetime import datetime, date
from decimal import Decimal


class OhioSectionDict(TypedDict):
    """Generated from OhioSection Pydantic model - DO NOT EDIT"""
    section_number: NotRequired[str]
    url: NotRequired[str]
    url_hash: NotRequired[str]
    header: NotRequired[str]
    section_title: NotRequired[str]
    paragraphs: NotRequired[List[str]]
    full_text: NotRequired[str]
    word_count: NotRequired[int]
    paragraph_count: NotRequired[int]
    has_citations: NotRequired[bool]
    citation_count: NotRequired[int]
    in_complex_chain: NotRequired[bool]
    is_clickable: NotRequired[bool]
    scraped_date: NotRequired[str]
    enrichment: NotRequired[Dict[str, Any]]
    treatment_status: NotRequired[str]
    invalidated_by: NotRequired[str]
    superseded_by: NotRequired[str]
    valid_from: NotRequired[str]
    valid_until: NotRequired[str]
    authority_score: NotRequired[float]
    betweenness_centrality: NotRequired[float]
    citation_velocity: NotRequired[float]
    court_level: NotRequired[str]
    binding_on: NotRequired[List[str]]
    precedent_value: NotRequired[str]
    title: NotRequired[str]
    chapter: NotRequired[str]


class CitationDataDict(TypedDict):
    """Generated from CitationData Pydantic model - DO NOT EDIT"""
    section: NotRequired[str]
    direct_references: NotRequired[List[str]]
    reference_count: NotRequired[int]
    references_details: NotRequired[List[Dict[str, Any]]]


class ReverseCitationDataDict(TypedDict):
    """Generated from ReverseCitationData Pydantic model - DO NOT EDIT"""
    section: NotRequired[str]
    cited_by: NotRequired[List[str]]
    cited_by_count: NotRequired[int]
    citing_details: NotRequired[List[Dict[str, Any]]]


class CitationChainDict(TypedDict):
    """Generated from CitationChain Pydantic model - DO NOT EDIT"""
    chain_id: NotRequired[str]
    primary_section: NotRequired[str]
    chain_sections: NotRequired[List[str]]
    chain_depth: NotRequired[int]
    references_count: NotRequired[int]
    created_at: NotRequired[str]
    complete_chain: NotRequired[List[Dict[str, Any]]]


class CorpusInfoDict(TypedDict):
    """Generated from CorpusInfo Pydantic model - DO NOT EDIT"""
    total_sections: NotRequired[int]
    sections_with_citations: NotRequired[int]
    complex_chains: NotRequired[int]
    reverse_citations: NotRequired[int]
    build_date: NotRequired[str]
    source: NotRequired[str]
    version: NotRequired[str]
    builder: NotRequired[str]
    databases: NotRequired[List[str]]


class ReferenceDetailDict(TypedDict):
    """Generated from ReferenceDetail Pydantic model - DO NOT EDIT"""
    section: NotRequired[str]
    title: NotRequired[str]
    url: NotRequired[str]
    url_hash: NotRequired[str]
    context: NotRequired[str]
    relationship: NotRequired[str]
    position: NotRequired[int]


class CitingDetailDict(TypedDict):
    """Generated from CitingDetail Pydantic model - DO NOT EDIT"""
    section: NotRequired[str]
    title: NotRequired[str]
    url: NotRequired[str]
